### ISSUE TITLE
A call to SSPI failed, see inner exception

### ISSUE THREAD

**Issue by AlexO64** [MonkeyBinBin/TokenbasedAPNsSample#2]
Dear sir,
I tried you solution few month ago and it was working,
But today I finally have time to work with this and have  a Problem - get error
Message	"A call to SSPI failed, see inner exception."	string with inner exception
Message	"The message received was unexpected or badly formatted"
Do you have any idea what is going on and if no then second wuestion is: is it working right now for you?
Thank you very much
Alex

![image](https://user-images.githubusercontent.com/27639540/28543535-fa58dc2a-7074-11e7-8523-bd9cf0ed422a.png)

**Comment by MonkeyBinBin** [comment]
Hi,
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

Your system need support TLS 1.2 or higher.
I use windows 10 to run the application is successful.
You can refer to the following URL
https://blogs.msdn.microsoft.com/kaushal/2011/10/02/support-for-ssltls-protocols-on-windows/

**Comment by tenbit** [comment]
hwo to support win7?

**Comment by AlexO64** [comment]
I install it on Windows 10 and everything is working now
